http:
  routers:
    web1:
      rule: "Host(`web1.local`)"
      service: web1-service
      entryPoints:
        - web

    web2:
      rule: "Host(`web2.local`)"
      service: web2-service
      entryPoints:
        - web

  services:
    web1-service:
      loadBalancer:
        servers:
          - url: "http://192.168.56.10:3000"

    web2-service:
      loadBalancer:
        servers:
          - url: "http://192.168.56.11:3001"
