---

- name: Install required packages
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: yes

- name: Start and enable MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Change MySQL root authentication to native password
  community.mysql.mysql_user:
    name: root
    host: localhost
    plugin: mysql_native_password
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: true

- name: Set MySQL root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present

- name: Create application database
  community.mysql.mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create application user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_db_name }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    column_case_sensitive: false

- name: Allow remote access from webservers
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MySQL

- name: Upload and run schema script
  template:
    src: init.sql.j2
    dest: /tmp/init.sql

- name: Apply initial schema
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: import
    target: /tmp/init.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"
